name: leancode_cubit_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.0.0
  copy_with_extension: ^5.0.4
  cqrs: ^10.0.1
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  leancode_hooks: ^0.0.6
  logging: ^1.0.0
  provider: ^6.0.0
  sliver_tools: ^0.2.12

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0
  mocktail: ^1.0.0