name: publish leancode_cubit_utils

on:
  push:
    tags: ['leancode_cubit_utils-v*']

jobs:
  publish:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    defaults:
      run:
        working-directory: packages/leancode_cubit_utils

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.x
          cache: true

      - name: Publish and release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          path: packages/leancode_cubit_utils
